---
language: node_js

before_install:
- '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
- npm install -g npm@latest

install:
  - "gem install sass"

script:
  - sass --watch tests/main.scss:tests/main.css

branches:
  only:
    - master